<%-- 
    Document   : Calendar
    Created on : Jul 10, 2025, 11:14:34 PM
    Author     : DELL
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar - Quản lý lịch trình</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <!-- Debug Info -->
    <div class="bg-yellow-100 p-4 mb-4">
        <h2 class="text-lg font-bold">Debug Info:</h2>
        <p>Calendars count: ${calendars != null ? calendars.size() : 'NULL'}</p>
        <p>Session ID: ${pageContext.session.id}</p>
        <p>Current time: <%= new java.util.Date() %></p>
    </div>

    <div class="container mx-auto p-4">
        <div class="bg-white rounded-lg shadow-lg p-6">
            <h1 class="text-2xl font-bold text-gray-800 mb-4">Calendar System</h1>
            
            <!-- Calendar List -->
            <div class="mb-6">
                <h2 class="text-lg font-semibold mb-3">Danh sách lịch:</h2>
                <c:choose>
                    <c:when test="${not empty calendars}">
                        <div class="space-y-2">
                            <c:forEach var="calendar" items="${calendars}">
                                <div class="flex items-center space-x-3 p-3 bg-gray-50 rounded-lg">
                                    <div class="w-4 h-4 rounded-full" style="background-color: ${calendar.color}"></div>
                                    <span class="text-gray-700">${calendar.name}</span>
                                    <span class="text-sm text-gray-500">(ID: ${calendar.idCalendar})</span>
                                </div>
                            </c:forEach>
                        </div>
                    </c:when>
                    <c:otherwise>
                        <div class="text-gray-500 p-4 bg-gray-50 rounded-lg">
                            Chưa có lịch nào trong hệ thống
                        </div>
                    </c:otherwise>
                </c:choose>
            </div>

            <!-- Simple Calendar Grid -->
            <div class="mb-6">
                <h2 class="text-lg font-semibold mb-3">Lịch tháng hiện tại:</h2>
                <div class="grid grid-cols-7 gap-1 bg-white border rounded-lg overflow-hidden">
                    <!-- Weekday headers -->
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">CN</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T2</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T3</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T4</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T5</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T6</div>
                    <div class="p-2 text-center font-medium text-gray-500 bg-gray-100">T7</div>
                    
                    <!-- Calendar days -->
                    <div id="calendarDays" class="col-span-7 grid grid-cols-7">
                        <!-- Days will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Action Buttons -->
            <div class="flex space-x-4">
                <button id="addEvent" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
                    <i class="fas fa-plus mr-2"></i>Tạo sự kiện
                </button>
                <button id="refreshBtn" class="bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700">
                    <i class="fas fa-refresh mr-2"></i>Làm mới
                </button>
            </div>
        </div>
    </div>

    <script>
        console.log('Calendar page loaded');
        
        // Simple calendar rendering
        function renderCalendar() {
            const calendarDays = document.getElementById('calendarDays');
            const today = new Date();
            const year = today.getFullYear();
            const month = today.getMonth();
            
            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            
            let html = '';
            
            // Add empty cells for days before the first day of the month
            for (let i = 0; i < firstDay; i++) {
                html += '<div class="p-2 text-center text-gray-300 bg-gray-50"></div>';
            }
            
            // Add days of the month
            for (let day = 1; day <= daysInMonth; day++) {
                const isToday = day === today.getDate();
                const dayClass = isToday ? 'bg-blue-100 text-blue-600 font-bold' : 'text-gray-700';
                
                html += `<div class="p-2 text-center ${dayClass} hover:bg-gray-50 cursor-pointer">${day}</div>`;
            }
            
            calendarDays.innerHTML = html;
        }
        
        // Event listeners
        document.addEventListener('DOMContentLoaded', function() {
            console.log('DOM loaded');
            renderCalendar();
            
            document.getElementById('addEvent').addEventListener('click', function() {
                alert('Chức năng tạo sự kiện sẽ được thêm sau!');
            });
            
            document.getElementById('refreshBtn').addEventListener('click', function() {
                location.reload();
            });
        });
    </script>
</body>
</html>
